name: ass6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Frame 5.png
    - assets/logo-79.png
    - assets/Frame 8.png
    - assets/Frame 9.png
    - assets/Frame 2.png
    - assets/Frame 9-2.png
    - assets/Group 780.png
    - assets/Ellipse 1096.png
    - assets/Ellipse 1096-2.png
    - assets/Ellipse 1096-3.png
    - assets/Ellipse 1096-4.png
    - assets/star.png
    - assets/Mask group.png
    - assets/img123.png
    - assets/image 7.png
    - assets/image 8.png
    - assets/Frame 1000001585.png
    - assets/image 5.png
    - assets/confident-businessman-stands-luxury-boutique-generated-by-ai 1.png
    - assets/image 5-2.png




